[package]
name = "rustfastq"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-htslib ="0.43.1"
counter = "0.5"
bktree = "1"
polars = {version = "0.29", features =["parquet", "lazy"]}
streaming_algorithms = "*"
indicatif = "0.17"
clap = { version = "4", features = ["derive"] }
rustbustools = { path = "/home/michi/Dropbox/rustbustools" }
itertools="0.10.5"

