[package]
name = "rustfastq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# flate2 = "1.0"
rust-htslib ="0.39"
# regex = "1"
# lazy_static = "1"
# serde = { version = "1.0", features = ["derive"] }
# serde_json = "1.0"
# rusqlite = "0.27"
# fastq = "0.6"
counter = "0.5"
bktree = "1"
polars = "0.21"
streaming_algorithms = "*"