[package]
name = "rustfastq"
version = "0.3.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-htslib ="0.45.0"
counter = "0.5"
polars = {version = "0.37.0", features =["parquet", "lazy"]}
indicatif = "0.17"
clap = { version = "4", features = ["derive"] }
itertools="0.12.1"
regex = "*"
